### ISSUE TITLE
요청에 body 가 json이 아닌경우, javascript 에러 메세지 노출

### ISSUE THREAD

**Issue by Skyrich2000** [rkskekzzz/APITester_For_Notion#4]
# 현재 상황

요청시, body가 내용이 없거나 json이 아닌경우, 결과 창이 다음과 같이 출력됩니다.

<img width="518" alt="스크린샷 2022-01-03 오후 5 48 43" src="https://user-images.githubusercontent.com/46391729/147912772-15b53eee-3c1a-4d92-a363-958bdc04357f.png">

`<ReactJson src={response} />`이렇게 되어있어서 response 가 json 이 아니면 저렇게 뜨는거같아요

# 요구 사항

json 이 아닌경우에는 문자열로 출력하게 해야할거같습니다

**Comment by rkskekzzz** [comment]
이문제는 지금 저는 안나는 것 같은데 다음에 어떤 값을 넣었을 때 나오는지 알려주시면 해결해보겠습니다

**Comment by Skyrich2000** [comment]
[이](https://heyinsa.kr/apitester?method=GET&url=https://heyinsa.kr/dueldice/api/users/no-user&header=%7B%0A%20%20%22Authorization%22:%20%22Bearer%20test_access_token%22%0A%7D&mode=light) API에서는 에러가 나요

**Comment by Skyrich2000** [comment]
일단 대강 수정하긴했는데, typography 를 멋대로 쓴거라 리뷰한번 부탁드립니다..

**Comment by rkskekzzz** [comment]
적절한 것 같아용!
