### ISSUE TITLE
header 에 한글 들어가는경우, 오류

### ISSUE THREAD

**Issue by Skyrich2000** [rkskekzzz/APITester_For_Notion#5]
header 에 한글이 포함되어있는경우, 요청이 이뤄지지 않고, 빈 결과창이 뜹니다.

conlose log 를 보면, Axios 오류가 나 있습니다.

**Comment by rkskekzzz** [comment]
확인해볼게요 ㅜㅜ

**Comment by Skyrich2000** [comment]
원래 header 에는 한글이 들어가면 안되는거네요 ㅎㅎ
